Поправил уровни абстракции
Vi-812/git_check_alive pull request #10
Opened 2023-01-16 21:02 UTC by Vi-812

Поправил уровни абстракции

2023-01-17 16:06 UTC, alex-karo requested changes

2023-01-17 16:06 UTC, alex-karo commented on graphql.py
> +    ТОЖЕ ОПИСАТЕЛЬНОЕ
В чем смысл этого комментария?

2023-01-17 16:06 UTC, alex-karo commented on graphql.py
> +        try:
Этот код дублируется уже в двух методах
Так же, как и формат запроса (json с query и variables)
И будет дублироваться в других, верно?

2023-01-17 16:07 UTC, Vi-812 commented on graphql.py
> +    ТОЖЕ ОПИСАТЕЛЬНОЕ
Чтоб не забыть сделать описание класса когда он будет окончательным)

2023-01-17 16:09 UTC, Vi-812 commented on graphql.py
> +        try:
Это запрос курсора для текущего элемента, я его вообще не использую, могу убрать даже, предполагаю что никогда не понадобится.

2023-01-17 16:37 UTC, alex-karo commented on graphql.py
> +    ТОЖЕ ОПИСАТЕЛЬНОЕ
Лучше делай описание сразу
Если класс не отвечает описанию/названию - вероятно, это сигнал к тому, что его стоит разбить или переименовать

2023-01-19 10:47 UTC, Vi-812 commented on graphql.py
> +    ТОЖЕ ОПИСАТЕЛЬНОЕ
Тут будет краткое описание всех методов, что для чего и откуда вызывается. Пока это еще не готово(

2023-01-19 10:47 UTC, Vi-812 commented on graphql.py
> +        try:
Вынесено в класс Link

2023-01-23 07:42 UTC, alex-karo approved these changes

2023-01-23 07:47 UTC, merged